export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const DELETE_COMPLETION = "DELETE_COMPLETION";
export const FINISH_ITEM = "FINISH_ITEM";
export const UNFINISH_ITEM = "UNFINISH_ITEM";